CREATE DEFINER=`root`@`localhost` PROCEDURE `addNewVillagers`(
	IN nam nvarchar(50),
    iImage nvarchar(50),
    pImage nvarchar(50),
    hImage nvarchar(50),
    species nvarchar(50),
    gender nvarchar(50),
    personality nvarchar(50),
    hobby nvarchar(50),
    bday nvarchar(50),
    catchP nvarchar(50),
    favSong nvarchar(50),
    favSaying nvarchar(50),
    sty1 nvarchar(50),
    sty2 nvarchar(50),
	col1 nvarchar(50),
    col2 nvarchar(50),
    wallPap nvarchar(50),
    flooring nvarchar(50),
    furnList nvarchar(50),
    fName nvarchar(50),
    entryID nvarchar(50)
 )
BEGIN
INSERT INTO villagers VALUES(nam,
iImage,
pImage,
hImage,
species,
gender,
personality,
hobby,
bday,
catchP,
favSong,
favSaying,
sty1,
sty2,
col1,
col2,
wallPap,
flooring,
furnList,
fName,
entryID);

END